version: "3.8"

services:
  localstack:
    build: .
    container_name: localstack
    ports:
      - "4566:4566"

  nginx:
    build: ./nginx
    container_name: image-api-gateway
    depends_on:
      - localstack
    ports:
      - "8080:8080"
